### ISSUE TITLE
How to change the homepage ?

### ISSUE THREAD

**Issue by Darecjo** [eddiesigner/weiss-pro#16]
Well, im trying to change the home page to the tags page to show the tags at the start is there anyway to do it?

**Comment by eddiesigner** [comment]
You can follow these steps:

1. Create a backup of the theme

2. Unzip the theme file

3. Rename the file `page-tags.hbs` to `home.hbs`

4. Open the file `routes.yaml` with a code editor and replace all the content with this code:

```yaml
routes:
  /:     
    data: page.tags
    template: home
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
```

5. Save your changes

6. Zip the theme folder and upload it again

7. Upload the file `routes.yaml` in the Ghost Admin: Settings —> Labs —> Routes
