### ISSUE TITLE
Setting Static Home Page not receiving {{content}}

### ISSUE THREAD

**Issue by hwlmatt** [eddiesigner/weiss-pro#4]
I think I am missing a step in setting this up, and assume it is template related since it worked on other templates. If not, apologies, but your insight would be appreciated. :)

Neither `{{#page}} {{content}} {{/page}}` or `{{#post}} {{content}}{{/post}}` seem to output anything when I check the source of rendered page ( `site.com/` )

The page/route IS seeing and using the template, but not outputting the content entered into the editor.

My **_routes.yaml_** looks like this:

```
routes:
  /:
    data: page.home
    template: page-home
  /signup/:
    template: members/signup
    data: page.signup
  /signin/:
    template: members/signin
    data: page.signin
  /membership/:
    template: members/membership
    data: page.membership
  /account/:
    template: members/account
    data: page.account

collections:
  /read/:
    permalink: /read/{slug}/
    template: index
```
I have a page named home, with a route of `home` and a template `page-home.hbs` based originally on `index.hbs` but trimmed all the way down. The (i think) relevant parts of my `page-home.hbs` are:

```
{{!< default}}

<div class="main-wrap">
  {{> header}}

  <div>

    {{#post}}{{content}}{{/post}}

  </div>
  <p>Just some text to verify this template page is being used ;)</p>

</div>

{{!-- The #contentFor helper here will send everything inside it up to the matching #block helper found in default.hbs --}}

{{#contentFor "scripts"}}
<script defer src="{{asset "js/post.js"}}"></script>
{{/contentFor}}
```
I have also tried `{{#page}} {{content}} {{/page}}` with the same result.

Any insight on what I need to be doing to get this setup correctly would be greatly appreciated. 
Thank you.

Setting static homepage guide I was following:
The [static home page tutorial](https://ghost.org/tutorials/custom-home-page/) off of Ghost's docs

**Comment by eddiesigner** [comment]
Hi 👋🏼

First of all thank you for purchasing the theme!

According to the docs, the file `routes.yaml` has to look like this:

```
routes:
  /:
    data: page.home
    template: home
```

You're using `page-home` instead of `home` as the template.

Also you have to rename the file `page-home.hbs` to `home.hbs`

Then you have to render the content in `home.hbs` as follows:

```hbs
{{#page}}
  {{content}}
{{/page}}
```

After making those changes you have to upload the file `routes.yaml` again, zip the theme up, and upload it to the Design view in the Ghost admin.

I just tested it and it works 👍🏼
